apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sajid-khan-js/k8s-adventures
    targetRevision: HEAD
    path: argocd/app-repo2/helm
    helm:
      values: |
        image:
          tag: latest
        ingress:
          host: devopsi-paradox.10.0.0.100.xip.io
      version: v3
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
